version: '3'
services:
    nginx:
        build:
            dockerfile: ./docker/nginx/Dockerfile
            context: .
        ports:
            - 10081:80
        environment:
            TZ: "Asia/Tokyo"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - backend
            - frontend

    backend:
        build:
            dockerfile: ./docker/backend/Dockerfile
            context: .
            target: development
        env_file: ./dev.env
        volumes:
            - ./backend:/backend
        ports:
            - 8000:8000
        environment:
            TZ: "Asia/Tokyo"
        depends_on:
            - mysql

    frontend:
        build:
            dockerfile: ./docker/frontend/Dockerfile
            context: .
            target: development
        env_file: ./dev.env
        volumes:
            - ./frontend:/frontend
        ports:
            - 3000:3000

    mysql:
        build:
            dockerfile: ./docker/mysql/Dockerfile
            context: .
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "go-next-test"
            TZ: "Asia/Tokyo"
        ports: 
            - 3306:3306
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/mysql/data:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
